# TODO move to config / universal constant 



HOURS_PER_DAY = 24
DAYS_PER_YEAR = 365
N_INTERVALS_PER_HOUR = 4 # NUMBER OF TIMESTEPS => TODO! 
MINUTES_PER_HOUR = 60
LEN_INTERVAL = MINUTES_PER_HOUR // N_INTERVALS_PER_HOUR