# TODO move to config / universal constant
from datetime import time, date

YEAR = 2025

YEAR_START_DATE = date(YEAR, 1, 1)
YEAR_END_DATE = date(YEAR, 12, 31)

DAY_START_TIME = time(0, 0)
DAY_END_TIME = time(23, 59)

MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24
MINUTES_PER_DAY = HOURS_PER_DAY * MINUTES_PER_HOUR

DAYS_PER_YEAR = 365
MINUTES_PER_YEAR = DAYS_PER_YEAR * MINUTES_PER_DAY

N_INTERVALS_PER_HOUR = 4  # NUMBER OF TIMESTEPS => TODO!
LEN_INTERVAL = MINUTES_PER_HOUR // N_INTERVALS_PER_HOUR
